image: golang:1.13.5-alpine3.10

stages:
  - test
  - build
  - publish

before_script:
  - export DOCKER_REPOSITORY="canyan/rating-agent-hep"
  - export DOCKER_TAG=${CI_COMMIT_REF_SLUG:-master}
  - export SERVICE_IMAGE=$DOCKER_REPOSITORY:$DOCKER_TAG
  - export COMMIT_TAG="$CI_COMMIT_REF_SLUG"_"$CI_COMMIT_SHA"

test:unit:
  stage: test
  services:
    - redis:5.0-alpine
  variables:
    RATING_AGENT_HEP_REDIS_ADDRESS: "redis:6379"
  script:
    - apk add build-base gcc musl-dev xz-dev make
    - go get -u golang.org/x/lint/golint
    - make all
    - mkdir -p tests/unit-coverage && find . -name 'coverage.txt' -exec cp --parents {} ./tests/unit-coverage \;
    - tar -cvf $CI_PROJECT_DIR/unit-coverage.tar tests/unit-coverage
  artifacts:
    expire_in: 2w
    paths:
      - unit-coverage.tar

test:acceptance:kamailio:
  stage: test
  image: tiangolo/docker-with-compose
  services:
    - docker:19.03.5-dind
  before_script:
    - make docker-build-acceptance
    - make docker-start-kamailio
    - echo "Waiting for all the services to fully start up..."
    - sleep 10
  script:
    - make docker-test-kamailio
    - make docker-logs
    - make docker-stop
    - mkdir -p tests/kamailio-acceptance-coverage && find . -name 'coverage-acceptance.txt' -exec cp --parents {} ./tests/kamailio-acceptance-coverage \;
    - tar -cvf $CI_PROJECT_DIR/kamailio-acceptance-coverage.tar tests/kamailio-acceptance-coverage
  after_script:
    - make docker-logs || true
  artifacts:
    expire_in: 2w
    paths:
      - kamailio-acceptance-coverage.tar

test:acceptance:opensips:
  stage: test
  image: tiangolo/docker-with-compose
  services:
    - docker:19.03.5-dind
  before_script:
    - make docker-build-acceptance
    - make docker-start-opensips
    - echo "Waiting for all the services to fully start up..."
    - sleep 10
  script:
    - make docker-test-opensips
    - make docker-logs
    - make docker-stop
    - mkdir -p tests/opensips-acceptance-coverage && find . -name 'coverage-acceptance.txt' -exec cp --parents {} ./tests/opensips-acceptance-coverage \;
    - tar -cvf $CI_PROJECT_DIR/opensips-acceptance-coverage.tar tests/opensips-acceptance-coverage
  after_script:
    - make docker-logs || true
  artifacts:
    expire_in: 2w
    paths:
      - opensips-acceptance-coverage.tar

build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - echo "building rating-agent-hep for ${SERVICE_IMAGE}"
    - docker build -t $SERVICE_IMAGE .
    - docker save $SERVICE_IMAGE > image.tar
  artifacts:
    expire_in: 2w
    paths:
      - image.tar
  tags:
    - docker

publish:tests:
  stage: publish
  image: alpine
  before_script:
    - apk add --no-cache bash curl findutils git
  dependencies:
    - test:unit
    - test:acceptance:kamailio
    - test:acceptance:opensips
  script:
    - tar -xvf unit-coverage.tar
    - bash -c "bash <(curl -s https://codecov.io/bash) -Z -F unit -s ./tests/unit-coverage"
    - tar -xvf kamailio-acceptance-coverage.tar
    - bash -c "bash <(curl -s https://codecov.io/bash) -Z -F acceptancekamailio -s ./tests/kamailio-acceptance-coverage"
    - tar -xvf opensips-acceptance-coverage.tar
    - bash -c "bash <(curl -s https://codecov.io/bash) -Z -F acceptanceopensips -s ./tests/opensips-acceptance-coverage"

publish:build:
  stage: publish
  image: docker
  only:
    - /^(master|[0-9]+\.[0-9]+\.x)$/
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker load -i image.tar
    - docker tag $SERVICE_IMAGE $DOCKER_REPOSITORY:$COMMIT_TAG
    - docker tag $SERVICE_IMAGE $DOCKER_REPOSITORY:$CI_COMMIT_REF_SLUG
    - echo -n $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker push $DOCKER_REPOSITORY:$COMMIT_TAG
    - docker push $SERVICE_IMAGE
  tags:
    - docker
