version: '2.1'
services:

  #
  # The HEP protocol agent
  #
  rating-agent-hep:
    image: 'canyan/rating-agent-hep:master'
    environment:
    - RATING_AGENT_HEP_MESSAGE_BUS_URI=amqp://user:password@rabbitmq:5672//
    depends_on:
    - rabbitmq
    restart: always
