version: '2.1'
services:

  #
  # tester container, using canyan-tester
  #
  tester:
    image: 'canyan/canyan-tester:master'
    environment:
      TARGET: kamailio:5060
    volumes:
      - "./tests/:/tests/"
    command: sh -c "while true; do sleep 5; done;"
