version: '2.1'
services:

  #
  # The HEP protocol agent
  #
  rating-agent-hep:
    image: 'canyan/rating-agent-hep:master'
    environment:
    - RATING_AGENT_HEP_MESSAGE_BUS_URI=amqp://user:password@rabbitmq:5672//
    - RATING_AGENT_HEP_REDIS_ADDRESS=redis:6379
    - RATING_AGENT_HEP_SIP_LOCAL_DOMAINS=sip.canyan.io
    depends_on:
    - rabbitmq
    - redis
    restart: always
